title: Profile
description: This is my profile repository.
url: "https://sbahrami.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal # You can change this to any Jekyll theme you prefer

# Build settings
# markdown: kramdown
